"use client";

import { useState } from "react";
import type { AiMode, Citation } from "@/lib/api";

/**
 * Labelling and sourcing for everything the AI layer produces.
 *
 * Two rules the whole app follows, and this file is how they are kept:
 *
 * 1. **AI output is always labelled as AI.** A learner deciding whether to
 *    override a warning deserves to know whether the sentence in front of them
 *    was measured by a rule or written by a model. The two carry different
 *    weight, and only one of them affects their score.
 * 2. **Every AI claim shows its sources.** Grounding the model is pointless if
 *    the learner cannot see what it was grounded in. Citations collapse by
 *    default so they inform without shouting.
 */

const MODE_COPY: Record<AiMode, { label: string; hint: string }> = {
  generated: { label: "AI", hint: "Written by DolFin's AI coach from your own record." },
  cached: { label: "AI", hint: "Written by DolFin's AI coach; reused since your record hasn't changed." },
  offline: {
    label: "Offline",
    hint: "The AI coach is unavailable, so this was assembled from your counted records instead.",
  },
  skipped: { label: "Not analysed", hint: "There wasn't enough to analyse here." },
  grounding_failed: {
    label: "No material",
    hint: "DolFin had nothing in its library to ground an answer in, so it declined rather than guessing.",
  },
};

/** Small badge naming who produced a piece of text.
 *
 *  Renders nothing for "none": when no rule fired there is no explanation to
 *  attribute, and a badge on a plain confirmation would just be noise. */
export function AiBadge({
  mode,
  className = "",
}: {
  mode: AiMode | "none";
  className?: string;
}) {
  if (mode === "none") return null;
  const copy = MODE_COPY[mode] ?? MODE_COPY.offline;
  const tone =
    mode === "generated" || mode === "cached"
      ? "bg-violet-100 text-violet-800"
      : "bg-slate-100 text-slate-600";

  return (
    <span
      title={copy.hint}
      className={`rounded px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${tone} ${className}`}
    >
      {copy.label}
    </span>
  );
}

/** Sits under any AI panel to restate that none of it moves the score. */
export function AdvisoryNote({ children }: { children?: React.ReactNode }) {
  return (
    <p className="mt-3 text-xs text-slate-500">
      {children ??
        "This is the AI layer's read on your record. It's advisory — your Readiness Score is computed only from the deterministic rules, so nothing here moves it."}
    </p>
  );
}

/**
 * The educational-purpose disclaimer.
 *
 * Required on every surface that renders AI-generated content. This is not
 * decoration: specific buy/sell guidance is regulated investment advice in India,
 * and a learner reading a generated paragraph about their own portfolio needs the
 * line between teaching and advice stated rather than implied.
 *
 * `compact` is for inline use in a modal, where a full block would push the
 * actual decision below the fold.
 */
export function AiDisclaimer({ compact = false }: { compact?: boolean }) {
  const text =
    "Educational content only, generated by AI from DolFin's material and your practice " +
    "portfolio. Not investment advice, and it can be wrong — check the sources.";

  if (compact) {
    return (
      <p className="mt-2 text-[11px] leading-snug text-slate-400">{text}</p>
    );
  }

  return (
    <p className="mt-3 rounded-lg bg-slate-50 px-3 py-2 text-[11px] leading-relaxed text-slate-500">
      <span className="font-medium text-slate-600">Educational use only. </span>
      Generated by AI from DolFin&apos;s teaching material and your simulated practice
      portfolio. This is not investment advice, and AI can be wrong — the sources
      behind every answer are listed so you can check them.
    </p>
  );
}

const CORPUS_COPY: Record<Citation["corpus"], string> = {
  A: "DolFin's library",
  B: "Your own record",
  market: "Live market data",
};

/** Collapsible source list for an AI response. */
export function Citations({ citations }: { citations: Citation[] }) {
  const [open, setOpen] = useState(false);
  if (!citations.length) return null;

  // Group by corpus so the learner sees at a glance whether the answer used
  // their own record or only the general material.
  const groups = citations.reduce<Record<string, Citation[]>>((acc, c) => {
    (acc[c.corpus] ??= []).push(c);
    return acc;
  }, {});

  return (
    <div className="mt-3 border-t border-slate-100 pt-2">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        className="flex items-center gap-1.5 text-xs font-medium text-slate-500 hover:text-slate-700"
      >
        <span aria-hidden>{open ? "▾" : "▸"}</span>
        {citations.length} source{citations.length === 1 ? "" : "s"}
        <span className="font-normal text-slate-400">
          ({Object.keys(groups).map((k) => CORPUS_COPY[k as Citation["corpus"]]).join(", ")})
        </span>
      </button>

      {open && (
        <ul className="mt-2 space-y-1.5">
          {citations.map((c) => (
            <li key={c.chunk_id} className="text-xs text-slate-600">
              <span className="mr-1.5 rounded bg-slate-100 px-1 py-0.5 text-[10px] font-medium text-slate-500">
                {CORPUS_COPY[c.corpus]}
              </span>
              {c.source_reference ? (
                <a href={c.source_reference} className="underline hover:text-slate-900">
                  {c.source_title}
                </a>
              ) : (
                c.source_title
              )}
              {c.retrieved_at && (
                <span className="ml-1 text-slate-400">
                  · as of {new Date(c.retrieved_at).toLocaleString()}
                </span>
              )}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
