"""baseline schema with intervention lifecycle and equity curve

Revision ID: 19e245097d8a
Revises: 
Create Date: 2026-08-27 23:52:33.501232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e245097d8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('invested_cost', sa.Float(), nullable=False),
    sa.Column('unrealised_pnl', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('intervention_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_id', sa.String(), nullable=True))

    # Backfill before tightening the constraint. Rows written by the old code
    # left user_action NULL, and those are warnings we never learned the outcome
    # of, so "pending" is the honest value. Without this the ALTER below fails on
    # any database that already has intervention history.
    op.execute(
        "UPDATE intervention_logs SET user_action = 'pending' WHERE user_action IS NULL"
    )

    with op.batch_alter_table('intervention_logs', schema=None) as batch_op:
        batch_op.alter_column('user_action',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_intervention_logs_preview_id'), ['preview_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intervention_logs_user_action'), ['user_action'], unique=False)

    with op.batch_alter_table('reflections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reflections_preview_id'), ['preview_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reflections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reflections_preview_id'))
        batch_op.drop_column('preview_id')

    with op.batch_alter_table('intervention_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intervention_logs_user_action'))
        batch_op.drop_index(batch_op.f('ix_intervention_logs_preview_id'))
        batch_op.alter_column('user_action',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('preview_id')

    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_created_at'))

    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
