"""added reflection analysis columns

Revision ID: 750d286dc8ca
Revises: a7149c32deea
Create Date: 2026-08-30 19:43:26.343711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750d286dc8ca'
down_revision: Union[str, None] = 'a7149c32deea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reflections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning_class', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_response', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_citations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ai_mode', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reflections', schema=None) as batch_op:
        batch_op.drop_column('ai_mode')
        batch_op.drop_column('ai_citations')
        batch_op.drop_column('ai_response')
        batch_op.drop_column('reasoning_class')

    # ### end Alembic commands ###
