"""added AI reasoning layer tables

Revision ID: a7149c32deea
Revises: 19e245097d8a
Create Date: 2026-08-30 19:21:27.196247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7149c32deea'
down_revision: Union[str, None] = '19e245097d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_questions_concept'), ['concept'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_questions_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('corpus', sa.String(), nullable=False),
    sa.Column('chunk_key', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('source_title', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_key', name='uq_chunk_key')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_chunk_key'), ['chunk_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_corpus'), ['corpus'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('ai_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('preview_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('concept', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_findings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_findings_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_findings_preview_id'), ['preview_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_findings_user_id'), ['user_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('pattern_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('patterns', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('txn_count', sa.Integer(), nullable=False),
    sa.Column('resolved_intervention_count', sa.Integer(), nullable=False),
    sa.Column('quiz_attempt_count', sa.Integer(), nullable=False),
    sa.Column('reflection_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pattern_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pattern_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pattern_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('pattern_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pattern_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_pattern_analyses_created_at'))

    op.drop_table('pattern_analyses')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('ai_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_findings_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_findings_preview_id'))
        batch_op.drop_index(batch_op.f('ix_ai_findings_kind'))
        batch_op.drop_index(batch_op.f('ix_ai_findings_created_at'))

    op.drop_table('ai_findings')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_corpus'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_chunk_key'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('generated_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_generated_questions_concept'))

    op.drop_table('generated_questions')
    # ### end Alembic commands ###
